# MySQL. Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
# gem install mysql2
#
# And be sure to use new-style password hashing:
# http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#------------------------------------------------------------------------------
development: &development
      adapter: mysql2
      encoding: utf8
      database: sampleapp
      pool: 5
      username: root
      password:  cyhwasyj22
      host: localhost
test:
      <<: *development
      database: sampleapp

production:
      <<: *development
      database: sampleapp
